---
- name: Pull the image in production host and create the container
  hosts: Production_Host
  tasks:
    - name: Remove unused Images
      shell:
        cmd: docker system prune -f
    - name: Docker login
      shell:
        cmd: docker login
    - name: Pulling the Image
      shell:
        cmd: docker pull vinayak96/scientific_calculator:latest
    - name: Removing old Container
      shell:
        cmd: docker rm prod_calc
    - name: Creating new Container
      shell:
        cmd: docker create -it --name prod_calc vinayak96/scientific_calculator:latest
    - name: Docker Logout
      shell:
        cmd: docker logout