---
- name: Creating Docker image and pushing to docker hub
  hosts: server
  tasks:
    - name: Creating a docker container
      shell:
        cmd: docker build /var/lib/jenkins/workspace/Scientific\ Calculator/ -t vinayak96/scientific_calculator:latest
    - name: Push image to docker hub
      shell:
        cmd: docker push vinayak96/scientific_calculator:latest

